name: "dbaas"
uuid: "869a8c0e-b9c0-4515-8c69-3cdd2c3d95d0"
description: "Genesis DBaaS element"
schema_version: 1
version: "0.0.1"
api_version: "v1"

resources:
  $core.compute.nodes:
    dbaas_cp:
      uuid: "bcb1407f-269b-4e30-a104-c22e677483a2"
      name: dbaas_cp
      project_id: "12345678-c625-4fee-81d5-f691897b8142"
      root_disk_size: 15
      cores: 1
      ram: 1024
      image: http://repository.genesis-core.tech:8081/genesis-db/latest/genesis-db.raw.gz

  # TODO: Add DNS record when the Import/Export feature is added

  $dbaas.types.postgres.versions:
    pg18:
      uuid: "26786c09-d175-44e5-9013-ac14c88acd1c"
      name: "pg18"
      image: http://repository.genesis-core.tech:8081/genesis-db/latest/genesis-db-pg.raw.gz
