[db]
connection_url = postgresql://genesis_db:pass@localhost:5432/genesis_db


[logging]
config = logging.yaml


[iam]
# token_encryption_algorithm = HS256


[HS256]
# encryption_key = secret

[user_api]
bind_host = 0.0.0.0

[status_api]
bind_host = 0.0.0.0

[orch_api]
bind_host = 0.0.0.0


[launchpad]
services =
    genesis_db.infra.services.builder:CoreInfraBuilder,
    gcl_sdk.agents.universal.services.scheduler:UniversalAgentSchedulerService,
    gcl_sdk.agents.universal.services.agent:UniversalAgentService,
    genesis_db.paas.services.builder:PGInstanceBuilder,


[genesis_db.infra.services.builder:CoreInfraBuilder]
instance_model = genesis_db.infra.dm.models:PGInstance
project_id = 11111112-f41d-40ff-b530-e8f4e70b53ca