[DEFAULT]
verbose = True
debug = True

[universal_agent]
uuid5_name = dbaas
payload_path = /var/lib/exordos/exordos_db/payload.json
orch_endpoint = http://dbaas-cp.local.genesis-core.tech:11011
status_endpoint = http://dbaas-cp.local.genesis-core.tech:11012
caps_drivers = PGCapabilityDriver
