name: build

on:
  push:

env:
  ARTIFACTS_PATH: artifacts
  CORE_BRANCH: "master"
  # Space-separated list of elements to install as dependencies
  ELEMENT_DEPS: ""
  PACKER_VERSION: "1.9.2"
  CORE_ENDPOINT_URL: http://10.20.0.2:80/api/core
  CORE_USERNAME: "admin"
  CORE_PASSWORD: "admin"
  ELEMENT_NAME: dbaas

jobs:
  BuildTestPush:
    runs-on: ubuntu-24.04
    if : ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}
      - name: Install exordos
        run: curl -fsSL https://repo.exordos.com/install.sh | sudo sh
      - name: Install hypervisor
        run: |
          sudo exordos compute hypervisors init
          sudo chmod 666 /dev/kvm
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Build Exordos DB
        timeout-minutes: 20
        env:
          PUSH_EXORDOS_CFG: ${{ secrets.PUSH_EXORDOS_CFG }}
        run: |
          set -eux

          mkdir -p ${ARTIFACTS_PATH}

          VERSION="$(exordos get-version .)"

          exordos build $(pwd)

          echo "$PUSH_EXORDOS_CFG" | base64 -d > exordos/exordos.push.yaml
          exordos push -c exordos/exordos.push.yaml -t exordos_repo -f --latest

          echo "${VERSION}" > "${ARTIFACTS_PATH}/version.txt"
      - name: Upload the build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build_artifacts
          path: artifacts/
      - name: set exordos config
        run: |
          exordos settings set-realm default --endpoint $CORE_ENDPOINT_URL
          exordos settings set-context default --name default --user $CORE_USERNAME --password $CORE_PASSWORD
      - name: Bootstrap exordos_core
        run:
          exordos bootstrap -i latest -f -m core --admin-password $CORE_PASSWORD --cidr 10.20.0.0/22
      - name: Wait for Exordos Core API
        run: |
          for i in {1..60}; do
            if exordos ready_api; then
              echo "Exordos Core API is ready"
              break
            fi
            echo "Waiting for Exordos Core API... ($i/60)"
            sleep 5
          done
      - name: Set hypervisor with overbooking
        run: |
          HYPER_UUID="$(exordos c h l -o json | jq -r .[0]."uuid")"
          exordos compute hypervisors update $HYPER_UUID --cores-ratio 10.0 --ram-ratio 10.0
      - name: Preload dependencies in background
        run: |
          for dep in $ELEMENT_DEPS; do
            exordos e elements install $dep
          done
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: build_artifacts
          path: artifacts/
      - name: install dbaas
        run: |
          VERSION=$(cat artifacts/version.txt)
          exordos e e install $ELEMENT_NAME -v $VERSION
      - name: check exordos dbaas
        timeout-minutes: 10
        run: |
          set -eux

          while [ $(exordos ee l -o json -f name=$ELEMENT_NAME | jq -r .[0]."status") != "ACTIVE" ]; do
            sleep 5
          done

          exordos e e show $ELEMENT_NAME
      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true
          wait-timeout-minutes: 15
